app/urls.py
from django.urls import path, include
from django.contrib import admin
from movies.views import movie_upload_from_csv, channel_upload_from_csv, episode_upload_from_csv, ChannelView, ChannelDetailView, LatestRateView,generate_video_view, list_created_files
import debug_toolbar
import app.views as views

urlpatterns = [
    path('api/v1/users', include('users.urls')),
    path("api/v1/movies", include("movies.urls")),
    path("api/v1/feeds", include("feed.urls")),
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('api/v1/notices', views.NoticeView.as_view()),
    path('api/v1/channels', ChannelView.as_view()),
    path('api/v1/channels/<int:channel_id>', ChannelDetailView.as_view()),
    path('api/v1/movie_upload', movie_upload_from_csv, name='movie_upload'),
    path('api/v1/channel_upload', channel_upload_from_csv, name='channel_upload'),
    path('api/v1/episode_upload', episode_upload_from_csv, name='episode_upload'),
    path('api/v1/latest-ratings', LatestRateView.as_view()),
    path('api/v1/common/reply', views.ReplyView.as_view(), name='reply'),
    path('api/v1/common/reply/<int:reply_id>', views.ReplyDetailView.as_view(), name='reply-detail'),
    path('api/v1/common/reply/<int:reply_id>/nested_reply', views.NestedReplyView.as_view(), name='nested-reply'),
    path('api/v1/common/reply/<int:reply_id>/nested_reply/<int:nested_reply_id>', views.NestedReplyDetailView.as_view(), name='nested-reply-detail'),
    path('api/v1/common/like', views.LikeView.as_view(), name='like'),
    path('api/v1/following', views.FollowingView.as_view(), name='following'),
    path('api/v1/following/<int:user_id>', views.FollowingUserDetailView.as_view(), name='following-user-detail'),
    path('api/v1/follower/<int:user_id>', views.FollowerUserDetailView.as_view(), name='follower-user-detail'),
    path('api/v1/generate_video', generate_video_view, name='generate_video'),
    path('api/v1/list-generate-video', list_created_files, name='list-generate-video'),   
]

movies/urls.py
from django.urls  import path

from movies.views import RateView, GenreMovieView, MovieView, MovieDetailView, CommentView, EpisodeMovieView, WishListView, LatestRateView, RankingView , PlayHistoryView, MainTopRankView, list_created_files, download_file

urlpatterns = [
    path("",MovieView.as_view()),
    path("/rankings", RankingView.as_view()),
    path("/main-top-rankings", MainTopRankView.as_view()),
    path('/<int:movie_id>', MovieDetailView.as_view()),
    path('/<int:movie_id>/user-rate', RateView.as_view()),
    path("/<int:movie_id>/comments",CommentView.as_view()),
    path('/<int:movie_id>/wishlist', WishListView.as_view()),
    path('/related-movies', GenreMovieView.as_view()),
    path('/<int:movie_id>/episodes', EpisodeMovieView.as_view()),
    path('/<int:movie_id>/playhistory', PlayHistoryView.as_view()),
    path('list-files/', list_created_files, name='list_created_files'),
    path('download/<str:directory>/<str:filename>/', download_file, name='download_file'),
]

s3/urls.py
from django.urls import path

from s3.views import s3_upload

# postman headers {"enctype" : "multipart/form-data"}, body form-data     key: file   value: 파일선택

urlpatterns = [
    path('upload', s3_upload, name='s3_upload'),
]

movies/forms.py
from django import forms
from django.core.validators import validate_email
import json

class ShortsVideoCreatorForm(forms.Form):
    title = forms.CharField(label='제목', max_length=100)
    voice_id = forms.CharField(label='클론 목소리 ID', max_length=100)
    videos_info = forms.CharField(widget=forms.HiddenInput(), required=False, label='비디오 정보')
    intro_text = forms.CharField(widget=forms.Textarea, label='인트로 텍스트', required=False)
    outro_text = forms.CharField(widget=forms.Textarea, label='아웃트로 텍스트', required=False)
    background_mp3 = forms.FileField(label='배경 음악 파일', required=False)
    intro_video_file = forms.FileField(label='인트로 비디오 파일', required=False)
    outro_video_file = forms.FileField(label='아웃트로 비디오 파일', required=False)

    def clean_videos_info(self):
        videos_info = self.cleaned_data.get('videos_info', '{}')  # 기본값을 '{}'로 설정
        try:
            videos_info_json = json.loads(videos_info)
        except json.JSONDecodeError:
            raise forms.ValidationError('비디오 정보가 올바른 JSON 형식이 아닙니다.')
        return videos_info_json

movies/views.py
import json
from json.decoder import JSONDecodeError
from decimal import *

from django.http import JsonResponse, HttpResponse, FileResponse, Http404
from django.views import View
from django.db.models import Q, Avg
from django.core.exceptions import ValidationError
from django.urls import reverse

from users.utils import login_decorator
from movies.models import Movie, MovieParticipant, Channel, Rating, MovieGenre, MovieEpisode, Episode, Genre, Country, WishList, PlayHistory
from movies.serializers import EpisodeSerializer
from django.shortcuts import render
from app.utils.youtube import get_channel_info, get_video_details,get_playlist_info, get_comments, get_highlights, comment, convert_PT_to_time
from datetime import datetime
from typing import Iterable
from collections import namedtuple
from bulk_update_or_create import BulkUpdateOrCreateQuerySet
import re
from datetime import datetime, timedelta
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from .forms import ShortsVideoCreatorForm
from app.utils.shorts import VideoCreator
import os
import requests

ManyToManySpec = namedtuple(
    "ManyToManySpec", ["from_object", "to_object"]
)


def bulk_create_manytomany_relations(
    model_from,
    field_name: str,
    model_from_name: str,
    model_to_name: str,
    specs: Iterable[ManyToManySpec]
):
    through_objs = []
    for spec in specs:
        through_objs.append(
            getattr(model_from, field_name).through(
                **{
                    f"{model_from_name.lower()}_id": spec.from_object.id,
                    f"{model_to_name.lower()}_id": spec.to_object.id,
                }
            )
        )
    getattr(model_from, field_name).through.objects.bulk_create(through_objs)

class ChannelView(View):
    @method_decorator(cache_page(60*60*24))
    def get(self, request):
        OFFSET = 0
        LIMIT  = 16

        channels = Channel.objects.all().order_by('-subscriber_count')
        channel_list = [{
            "id": channel.id,
            "channel_id"       : channel.channel_id,
            "handle"           : channel.handle,
            "title"            : channel.title,
            "description"      : channel.description,
            "published_at"     : channel.published_at,
            "thumbnail"        : channel.thumbnail,
            "view_count"       : channel.view_count,
            "subscriber_count" : channel.subscriber_count,
            "video_count"      : channel.video_count,
        } for channel in channels][OFFSET : LIMIT]

        return JsonResponse({"results" : channel_list}, status=200)
        # return HttpResponse('<html><body> channel ... cached</body></html>')

class ChannelDetailView(View):
    @method_decorator(cache_page(60*60*24))
    def get(self, request, channel_id):
        try:
            if not Channel.objects.filter(id=channel_id).exists():
                return JsonResponse({'MESSAGE' : 'Channel Not Exists'}, status = 404)

            channel = Channel.objects.get(id=channel_id)

            channel_details = {
                'channel_id'       : channel_id,
                'title'          : channel.title,
                'description'      : channel.description,
                'handle'           : channel.handle,
                'published_at'   : channel.published_at,
                'thumbnail'        : channel.thumbnail,
                'movie_list' : [{
                    "country_name"   : [country.name for country in movie.country.all()],
                    "movie_name"     : movie.title,
                    "movie_id"       : movie.id,
                    "running_time"   : sum([convert_PT_to_time(episode.duration) for episode in movie.episode.all()]),
                    "total_views"     : sum([episode.viewCount for episode in movie.episode.all()]),
                    "total_likes"     : sum([episode.likeCount for episode in movie.episode.all()]),
                    "total_comments"  : sum([episode.commentCount for episode in movie.episode.all()]),
                    "total_episodes"  : movie.episode.count(),
                    "released_date"  : movie.release_date,
                    "average_rating" : movie.average_rating,
                    "poster_image"   : movie.poster_image,
                    "trailer"        : movie.trailer,
                    "genres"         : [genre.name for genre in movie.genre.all()],
                } for movie in Movie.objects.filter(channel_id=channel_id)]
            }

            return JsonResponse({'channel_info' : channel_details}, status = 200)

        except KeyError:
            JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status=400)


class MovieView(View): 
    @method_decorator(cache_page(60*60*24))
    def get(self,request): 
        search = request.GET.get('search', '')
        country_name  = request.GET.get("country")
        genre1        = request.GET.get("genre1")
        genre2        = request.GET.get("genre2")
        rating        = request.GET.get("rating","")
        KOREAN_MOVIE  = "한국"
        FOREIGN_MOVIE = "외국"
        LIMIT         = 25
        OFFSET        = 0

        q = Q()
        
        if genre1 == "전체":
            genre1 = ""
        if country_name == KOREAN_MOVIE:
            q.add(Q(country__name=KOREAN_MOVIE), q.AND)

        if country_name == FOREIGN_MOVIE:
            q.add(~Q(country__name=KOREAN_MOVIE), q.AND)

        if genre1 or genre2:
            q.add(Q(genre__name=genre1)|Q(genre__name=genre2), q.AND)
        
        movies = Movie.objects.filter(q).order_by('-release_date').distinct()
        
        if search:
            movies = movies.filter(
                Q(description__icontains=search) | Q(title__icontains=search)
            ).distinct()

        if rating:
            movies =  Movie.objects.order_by('-average_rating')


        movie_list = [{
            "country_name"   : [country.name for country in movie.country.all()],
            "movie_name"     : movie.title,
            "movie_id"       : movie.id,
            # "running_time"   : sum([convert_PT_to_time(episode.duration) for episode in movie.episode.all()]),
            # "total_views"     : sum([episode.viewCount for episode in movie.episode.all()]),
            # "total_likes"     : sum([episode.likeCount for episode in movie.episode.all()]),
            # "total_comments"  : sum([episode.commentCount for episode in movie.episode.all()]),
            # "total_episodes"  : movie.episode.count(),
            "released_date"  : movie.release_date,
            "average_rating" : movie.average_rating,
            "poster_image"   : movie.poster_image,
            "trailer"        : movie.trailer,
            "genres"         : [genre.name for genre in movie.genre.all()],
        } for movie in movies ][OFFSET : LIMIT]

        return JsonResponse({"results" : movie_list, "page":OFFSET}, status=200)


class RateView(View):
    @login_decorator
    def post(self, request, movie_id):
        try:
            data = json.loads(request.body)
            print(request.body)
            print(data)
            rate = data['rate']

            Rating.objects.update_or_create(
                user_id  = request.user.id,
                movie_id = movie_id,
                defaults = {'rate' : rate}
            )

            mv_rate  = Rating.objects.filter(movie_id=movie_id)
            avg_rate = mv_rate.aggregate(avg_rate=Avg('rate'))
            
            Movie.objects.filter(id=movie_id).update(average_rating=avg_rate['avg_rate'])


            return JsonResponse({
                "message" : "SUCCESS"
            }, status=200)

        except KeyError:
            return JsonResponse({"message" : "INVALID FORMAT"}, status=400)
        
        except JSONDecodeError:
            return JsonResponse({"message" : "NO DATA"}, status=400)
        
        except ValidationError:
            return JsonResponse({"message" : "TYPE DOESNT MATCH"}, status=400)
    
    @login_decorator
    def get(self, request, movie_id):
        
        if Rating.objects.filter(user_id=request.user.id, movie_id=movie_id).exists():
                rate = Rating.objects.get(user_id=request.user.id, movie_id = movie_id).rate
        else:
            rate = 0.0

        return JsonResponse({"user_rate" : rate}, status=200)


class GenreMovieView(View):

    @method_decorator(cache_page(60*60*24))
    def get(self, request):  
        OFFSET = 0
        LIMIT  = 16
        q      = Q()

        try:
            movie_id = request.GET.get('id', None)
            
            if not movie_id:
                return JsonResponse({"message" : "NO QUERY STRING"}, status=404)  
            
            if not MovieGenre.objects.filter(movie_id=movie_id).exists():
                return JsonResponse({"message" : "QUERY DOES NOT MATCH"}, status=404)

            genres = MovieGenre.objects.filter(movie_id=movie_id)

            related = []

            for genre in genres:
                q |= Q(genre__id = genre.genre_id)
            
            movie = MovieGenre.objects.select_related('movie').filter(q).exclude(movie_id=movie_id)
            
            related = [{
                "movie_id" : mv.movie.id,
                "title"    : mv.movie.title,
                "avg"      : mv.movie.average_rating,
                "poster"   : mv.movie.poster_image,    
            }for mv in movie]
            
            related_movies = list({rel['title']: rel for rel in related}.values())
            
            return JsonResponse({
                "message" : "SUCCESS",
                "related_movies" : related_movies[OFFSET:LIMIT],
            },status=200)
        
        except KeyError:
            return JsonResponse({"message": "INVALID DATA FORMAT"}, status=400)


class MovieDetailView(View):

    @method_decorator(cache_page(60*60*24))
    def get(self, request, movie_id):
        try:

movies/templates/channel_upload_csv.html
{% block raw %}
<div class="container">
  <div class="row">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true"></span>
      </button>
    </div>
    {% endfor %} {% endif %}
    <div class="col-lg-12">
      <form
        action="{% url 'channel_upload' %}"
        method="POST"
        enctype="multipart/form-data"
      >
        {% csrf_token %}

        <div class="form-group">
          <label for="csvFile">채널 csv 파일을 업로드해주세요.</label>
          <input
            type="file"
            class="form-control"
            id="csv_file"
            name="csv_file"
          />
        </div>
        <button type="submit" class="btn btn-info btn-lg">등록</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

movies/templates/episode_upload_csv.html
{% block raw %}
<div class="container">
  <div class="row">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true"></span>
      </button>
    </div>
    {% endfor %} {% endif %}
    <div class="col-lg-12">
      <form
        action="{% url 'episode_upload' %}"
        method="POST"
        enctype="multipart/form-data"
      >
        {% csrf_token %}

        <div class="form-group">
          <label for="csvFile">Episode csv 파일을 업로드해주세요.</label>
          <input
            type="file"
            class="form-control"
            id="csv_file"
            name="csv_file"
          />
        </div>
        <button type="submit" class="btn btn-info btn-lg">에피소드 등록</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

movies/templates/generate_video.html
<!DOCTYPE html>
<html>
  <head>
    <title>AI 쇼츠 비디오 생성</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <!-- Bootstrap Material Design -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-material-design@4.1.2/dist/css/bootstrap-material-design.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-material-design@4.1.2/dist/js/bootstrap-material-design.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script>
      $(document).ready(function () {
        let videoCount = 0;
        let videosInfo = {}; // 비디오 정보를 저장할 객체

        function updateVideosInfo() {
          const jsonString = JSON.stringify(videosInfo);
          console.log(jsonString); // 콘솔에 JSON 문자열 출력
          $('#id_videos_info').val(jsonString);
        }

        $('#addVideo').click(function (e) {
          console.log('Clicked addVideo');
          e.preventDefault();
          videoCount++;
          const videoId = `video_${videoCount}`;
          videosInfo[videoId] = {
            url: '', // URL 필드 추가
            title: '',
            subtitle: '',
          };

          const videoFields = `
                <div class="video-group mb-3" id="video-group-${videoCount}">
                    <div class="form-group">
                        <label for="video_url_${videoCount}">비디오 URL:</label>
                        <input type="text" class="form-control video-url" data-video-id="${videoId}" placeholder="비디오 URL을 입력하세요" required>
                    </div>
                    <div class="form-group">
                        <label for="video_title_${videoCount}">제목:</label>
                        <input type="text" class="form-control video-title" data-video-id="${videoId}" placeholder="비디오 제목을 입력하세요" required>
                    </div>
                    <div class="form-group">
                        <label for="video_subtitle_${videoCount}">부제목:</label>
                        <input type="text" class="form-control video-subtitle" data-video-id="${videoId}" placeholder="비디오 부제목을 입력하세요" required>
                    </div>
                    <button type="button" class="btn btn-danger remove-video" data-target="#video-group-${videoCount}" data-video-id="${videoId}">제거</button>
                </div>
                `;
          $('#videosContainer').append(videoFields);

          // 비디오 정보 업데이트 함수 호출
          updateVideosInfo();
        });

        $(document).on(
          'change',
          '.video-url, .video-title, .video-subtitle',
          function () {
            const videoId = $(this).data('video-id');
            const fieldClass = $(this).attr('class').split(' ')[1];
            const fieldValue = $(this).val();

            // 입력된 값이 있는지 확인
            if (fieldValue.trim() !== '') {
              if (!videosInfo[videoId]) {
                videosInfo[videoId] = {};
              }
              if (fieldClass.includes('url')) {
                videosInfo[videoId].url = fieldValue;
              } else if (fieldClass.includes('title')) {
                videosInfo[videoId].title = fieldValue; // 제목 업데이트
              } else if (fieldClass.includes('subtitle')) {
                videosInfo[videoId].subtitle = fieldValue; // 부제목 업데이트
              }

              updateVideosInfo();
            }
          }
        );
      });
    </script>
  </head>
  <body>
    <div class="container mt-5">
      <h1 class="text-center mb-4">비디오 생성</h1>
      <form method="post" class="mt-3" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label for="title">{{ form.title.label }}</label>
          {{ form.title }}
        </div>
        <label for="voice_select">목소리 선택:</label>
        <select class="form-control" id="voice_select" name="voice_id">
          {% for voice in cloned_voices %}
          <option value="{{ voice.voice_id }}">{{ voice.name }}</option>
          {% endfor %}
        </select>

        <input type="hidden" id="id_videos_info" name="videos_info" value="" />
        <div id="videosContainer">
          <!-- 동적으로 추가될 비디오 필드가 위치할 컨테이너 -->
        </div>
        <button type="button" id="addVideo" class="btn btn-info mb-3">
          비디오 추가
        </button>

        <div class="form-group">
          <label for="intro_text">{{ form.intro_text.label }}</label>
          {{ form.intro_text }}
        </div>
        <div class="form-group">
          <label for="outro_text">{{ form.outro_text.label }}</label>
          {{ form.outro_text }}
        </div>
        <div class="form-group">
          <label for="background_mp3">{{ form.background_mp3.label }}</label>
          {{ form.background_mp3 }}
        </div>
        <div class="form-group">
          <label for="intro_video_file"
            >{{ form.intro_video_file.label }}</label
          >
          {{ form.intro_video_file }}
        </div>
        <div class="form-group">
          <label for="outro_video_file"
            >{{ form.outro_video_file.label }}</label
          >
          {{ form.outro_video_file }}
        </div>
        <button type="submit" class="btn btn-primary">생성</button>
      </form>
    </div>
    {% if form.errors %}
    <script>
      document.addEventListener('DOMContentLoaded', function() {
          var formErrors = {{ form.errors.as_json|safe }};
          // formErrors는 JSON 문자열이므로, 객체로 파싱합니다.
          try {
            var errors = JSON.parse(formErrors);

            // 에러 메시지 문자열을 생성합니다.
            var errorMessage = "";
            for (var field in errors) {
                if (errors.hasOwnProperty(field)) {
                    errorMessage += field + ": " + errors[field] + "\n";
                }
            }
        } catch (e) {
            console.error("JSON 파싱 오류:", e);
        }

          // 에러 메시지가 있으면 alert로 표시합니다.
          if (errorMessage) {
              alert("폼 제출에 문제가 있습니다:\n" + errorMessage);
          }
      });
    </script>
    {% endif %}
    <script>
      document.addEventListener('DOMContentLoaded', function () {
        const urlParams = new URLSearchParams(window.location.search);
        const success = urlParams.get('success');
        if (success) {
          alert('성공적으로 생성되었습니다.');
          window.history.replaceState(null, null, window.location.pathname); // URL에서 파라미터 제거
        }
      });
    </script>
  </body>
</html>

movies/templates/list_files.html
<!-- templates/list_files.html -->
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>생성된 파일 목록</title>
  </head>
  <body>
    <h1>생성된 파일 목록</h1>
    {% for directory, files_info in files_dict.items %}
    <h2>{{ directory }}</h2>
    <ul>
      {% for file in files_info %}
      <li>
        {% if file.type == 'video' %}
        <!-- 비디오 파일 재생 -->
        <video controls width="250">
          <source
            src="{% url 'download_file' directory file.name %}"
            type="video/mp4"
          />
          브라우저가 비디오 태그를 지원하지 않습니다.
        </video>
        {% elif file.type == 'audio' %}
        <!-- 오디오 파일 재생 -->
        <audio controls>
          <source
            src="{% url 'download_file' directory file.name %}"
            type="audio/mpeg"
          />
          브라우저가 오디오 태그를 지원하지 않습니다.
        </audio>
        {% else %}
        <!-- 기타 파일 다운로드 링크 -->
        <a href="{% url 'download_file' directory file.name %}"
          >{{ file.name }}</a
        >
        {% endif %}
      </li>
      {% endfor %}
    </ul>
    {% endfor %}
  </body>
</html>

movies/templates/playlist_upload_csv.html
{% block raw %}
<div class="container">
  <div class="row">
    {% if messages %} {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true"></span>
      </button>
    </div>
    {% endfor %} {% endif %}
    <div class="col-lg-12">
      <form
        action="{% url 'movie_upload' %}"
        method="POST"
        enctype="multipart/form-data"
      >
        {% csrf_token %}

        <div class="form-group">
          <label for="csvFile">Playlist csv 파일을 업로드해주세요.</label>
          <input
            type="file"
            class="form-control"
            id="csv_file"
            name="csv_file"
          />
        </div>
        <button type="submit" class="btn btn-info btn-lg">
          플레이리스트 등록
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}